version: "3"
services:
  wiki:
    build:
      context: .
      args:
        TW_PLUGIN_NAME: $TW_PLUGIN_NAME
        TW_BUILD_EDITION: $TW_BUILD_EDITION
        TW_VERSION: $TW_VERSION
    volumes:
    - ./src:/usr/src/tw5/plugins/${TW_PLUGIN_NAME}
    - ./output:/usr/src/tw5/editions/${TW_BUILD_EDITION}/output
    entrypoint:
    - node
    - ./tiddlywiki.js
    - ./editions/${TW_BUILD_EDITION}
    - --build
    - index
 